---
name: Build and Push ReactJS Image to Google Cloud Platform
on:
  push:
    branches: [main]
jobs:
  build-push-artr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: caravanalecturiireact
      PROJECT_ID: caravana-lecturii-330311
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./scripts/git_update.sh -v patch

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker europe-central2-docker.pkg.dev --quiet

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag $IMAGE_NAME:latest europe-central2-docker.pkg.dev/$PROJECT_ID/react-docker-repo/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest europe-central2-docker.pkg.dev/$PROJECT_ID/react-docker-repo/$IMAGE_NAME:$GIT_TAG
          docker push europe-central2-docker.pkg.dev/$PROJECT_ID/react-docker-repo/$IMAGE_NAME:latest
          docker push europe-central2-docker.pkg.dev/$PROJECT_ID/react-docker-repo/$IMAGE_NAME:$GIT_TAG
